version: '3'
services:
  spring:
    build: ./Spring
    image: rup/spring
    ports:
      - 8080:8080
    volumes:
      - ./Spring:/Spring
    environment:
      - TZ=Asia/Seoul
  mariadb:
    build: ./MariaDB
    image: rup/mariadb
    volumes:
      - ./MariaDB/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Seoul
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    restart: always
